name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cargo:
    runs-on: [self-hosted, "${{ matrix.os }}"]
    strategy:
      fail-fast: false
      matrix:
        os: [Windows]

    steps:
      - uses: actions/checkout@v2
      - uses: risc0/actions-rs-toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-sort
        uses: risc0/cargo-install@v1
        with:
          crate: cargo-sort
          version: "1.0"
      - run: cargo test -j 1 --release
      - run: cargo fmt --all -- --check
      - run: cargo sort --workspace --check
